### ISSUE TITLE
ubuntu virtual box doesn't exist

### ISSUE THREAD

**Issue by npapastefanakis** [lagotto/alm-report#162]
In file https://github.com/lagotto/alm-report/blob/master/Vagrantfile you have the line 

Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "chef/ubuntu-14.04"

The vagrant up command crashes with the message:

==> default: Box 'chef/ubuntu-14.04' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'chef/ubuntu-14.04'
    default: URL: https://atlas.hashicorp.com/chef/ubuntu-14.04
The box you're adding has a name different from the name you
requested. For boxes with metadata, you cannot override the name.
If you're adding a box using `vagrant box add`, don't specify
the `--name` parameter. If the box is being added via a Vagrantfile,
change the `config.vm.box` value to match the name below.

Requested name: chef/ubuntu-14.04
Actual name: bento/ubuntu-14.04

I guess that part of vagrant file must be:

  Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "bento/ubuntu-14.04"

**Comment by mfenner** [comment]
@npapastefanakis you are right. The box was recently renamed. I updated the Vagrantfile.
